services:
  codehouse:
    profiles: [production]
    image: codehouse:latest
    restart: unless-stopped
    env_file:
      - .env
    build:
      dockerfile: apps/codehouse/Dockerfile
      context: ../../