import type { Metadata } from 'next';

import './globals.css';

import { GeistMono } from 'geist/font/mono';
import { GeistSans } from 'geist/font/sans';

import { Layout } from '@/types/common';

import { cn } from '@/lib/utils';
import { GlobalProviders } from '@/providers/global-providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Layout) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={cn(GeistSans.variable, GeistMono.variable)}>
        <GlobalProviders>{children}</GlobalProviders>
      </body>
    </html>
  );
}
