packages:
  - "apps/*"
  - "packages/*"
onlyBuiltDependencies:
  - "@sentry/cli"
  - "@swc/core"
  - "core-js-pure"
  - "es5-ext"
  - "esbuild"
  - "sharp"
catalog:
  "@hookform/resolvers": "4.1.3"
  "@t3-oss/env-nextjs": "0.12.0"
  "@types/node": "20.17.24"
  "autoprefixer": "10.4.21"
  "class-variance-authority": "0.7.1"
  "clsx": "2.1.1"
  "country-flag-icons": "1.5.18"
  "date-fns": "4.1.0"
  "framer-motion": "12.5.0"
  "geist": "1.3.1"
  "import-in-the-middle": "1.13.1"
  "next": "15.2.2"
  "next-intl": "4.0.2"
  "next-runtime-env": "3.2.2"
  "next-themes": "0.4.6"
  "postcss": "8.5.3"
  "postcss-import": "16.1.0"
  "react-icons": "5.5.0"
  "require-in-the-middle": "7.5.2"
  "sharp": "0.33.5"
  "turbo": "2.4.4"
  "typescript": "5.8.2"
  "zod": "3.24.2"
catalogs:
  react18:
    "@types/react": "19.0.10"
    "@types/react-dom": "19.0.4"
    "react": "19.0.0"
    "react-dom": "19.0.0"
  eslint9:
    "@types/eslint": "9.6.1"
    "@typescript-eslint/eslint-plugin": "8.26.2-alpha.4"
    "@typescript-eslint/parser": "8.26.2-alpha.4"
    "eslint": "9.22.0"
    "eslint-config-next": "15.2.2"
    "eslint-config-prettier": "10.1.1"
    "eslint-config-turbo": "2.4.4"
    "eslint-plugin-only-warn": "1.1.0"
  tailwind4:
    "@tailwindcss/postcss": "4.0.14"
    "@tailwindcss/typography": "0.5.16"
    "tailwind-merge": "3.0.2"
    "tailwindcss": "4.0.14"
    "tailwindcss-animate": "^1.0.7"
