packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - '@sentry/cli'
  - '@swc/core'
  - core-js-pure
  - es5-ext
  - esbuild
  - sharp
catalog:
  '@hookform/resolvers': ^3.9.0
  '@t3-oss/env-nextjs': ^0.12.0
  '@types/node': ^20
  autoprefixer: ^10.4.20
  class-variance-authority: ^0.7.0
  clsx: ^2.1.0
  country-flag-icons: ^1.5.13
  date-fns: ^3.6.0
  framer-motion: ^11
  geist: ^1.3
  next-intl: ^4.0.2
  next-runtime-env: ^3.2.2
  next-themes: ^0.3.0
  next: ^14
  postcss-import: ^16.1.0
  postcss: ^8.4
  react-icons: ^5
  sharp: ^0.33.5
  tailwind-merge: ^2.2.2
  tailwindcss: ^3
  typescript: ^5
  zod: ^3
catalogs:
  react18:
    '@types/react': ^18.3.5
    '@types/react-dom': ^18.3.0
    react-dom: ^18.3.1
    react: ^18.3.1
  eslint8:
    '@types/eslint': ^8.56.7
    '@typescript-eslint/eslint-plugin': ^7.18.0
    '@typescript-eslint/parser': ^7.18.0
    '@vercel/style-guide': ^5.2.0
    eslint-config-next: ^14
    eslint-config-prettier: ^9.1.0
    eslint-config-turbo: ^2.1.1
    eslint-plugin-only-warn: ^1.1.0
    eslint: ^8.57.0
