packages:
  - 'apps/*'
  - 'packages/*'
onlyBuiltDependencies:
  - '@sentry/cli'
  - '@swc/core'
  - 'core-js-pure'
  - 'es5-ext'
  - 'esbuild'
  - 'sharp'
  - 'msw'
overrides:
  '@types/hast': 3.0.5
