module.exports = {
    plugins: ['@ianvs/prettier-plugin-sort-imports', 'prettier-plugin-tailwindcss'],
    semi: true,
    jsxSingleQuote: false,
    arrowParens: 'avoid',
    bracketSameLine: true,
    bracketSpacing: true,
    useTabs: false,
    tabWidth: 2,
    printWidth: 120,
    singleQuote: true,
    trailingComma: 'all',
    quoteProps: 'consistent',
    tailwindFunctions: ['twMerge', 'twJoin', 'cn', 'clsx', 'cva'],
    importOrder: [
        '<BUILTIN_MODULES>',
        '',
        '<THIRD_PARTY_MODULES>',
        '',
        '^(react/(.*)$)|^(react$)',
        '^(next/(.*)$)|^(next$)',
        '',
        '<TYPES>^react$',
        '<TYPES>',
        '^@/types/(.*)$',
        '',
        '^@/components/ui/(.*)$',
        '',
        '^@/components/(.*)$',
        '',
        '^@/constants/(.*)$',
        '',
        '^@/functions/(.*)$',
        '',
        '^@/hooks/(.*)$',
        '',
        '^@/routes/(.*)$',
        '',
        '^@/public/(.*)$',
        '',
        '^@/(.*)$',
        '',
        '^[./]',
        '',
        '^[./].*(css|scss)$',
    ],
    importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
};
