import './globals.css';

import { GeistMono } from 'geist/font/mono';
import { GeistSans } from 'geist/font/sans';

import localFont from 'next/font/local';

import type { ReactNode } from 'react';
import type { Metadata } from 'next';

import { GlobalProviders } from '@/components/global-providers';

import { cn } from '@/lib/utils';
import { getCurrentLocale } from '@/locales/server';

import { Header } from './components/header';

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

const LetsGoDigital = localFont({
  src: '../..//public/fonts/LetsGoDigital.ttf',
  variable: '--font-digital',
  weight: '400',
  style: 'normal',
  preload: true,
});

export default function RootLayout({ children }: { children: ReactNode }): JSX.Element {
  const locale = getCurrentLocale();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={cn(GeistSans.variable, GeistMono.variable, LetsGoDigital.variable)}>
        <GlobalProviders>
          <Header />
          {children}
        </GlobalProviders>
      </body>
    </html>
  );
}
