import "./globals.css";
import type {Metadata} from "next";
import type {ReactNode} from "react";
import localFont from "next/font/local";
import {GeistSans} from 'geist/font/sans';
import {GeistMono} from 'geist/font/mono';
import {cn} from "@/lib/utils";
import {Header} from "./components/header";
import {GlobalProviders} from "@/components/global-providers";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

const LetsGoDigital = localFont({
  src: '../../public/fonts/LetsGoDigital.ttf',
  variable: '--font-digital',
  weight: '400',
  style: 'normal',
  preload: true
});

export default function RootLayout({
                                     children,
                                   }: {
  children: ReactNode;
}): JSX.Element {
  return (
    <html lang="en" suppressHydrationWarning>
    <body className={cn(GeistSans.variable, GeistMono.variable, LetsGoDigital.variable)}>
    <GlobalProviders>
      <Header/>
      {children}
    </GlobalProviders>
    </body>
    </html>
  );
}


